import type { Metadata } from "next";
import { Kaushan_Script, Lato, Space_Mono } from "next/font/google";
import ReactQueryProvider from "@/components/Providers";

const kaushan_script = Kaushan_Script({
  subsets: ["latin"],
  variable: "--primary-font",
  weight: "400",
});

const space_mono = Space_Mono({
  subsets: ["latin"],
  variable: "--secondary-font",
  weight: "400",
});

const lato = Lato({
  subsets: ["latin"],
  variable: "--tertiary-font",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Prasanna Gramopadhye",
  description: "Generated by Prasanna Gramopadhye, using Next JS.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${kaushan_script.variable} ${space_mono.variable} ${lato.variable}`}
      >
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
